# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Q < Formula
  desc ""
  homepage "https://github.com/natesales/repo"
  version "0.8.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/natesales/q/releases/download/v0.8.1/q_0.8.1_darwin_arm64.tar.gz"
      sha256 "1c2046365807228d90ff09b3b3fad4ee1b6721efd7cc5d0ca1af1e503b927e8e"

      def install
        bin.install "q"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/natesales/q/releases/download/v0.8.1/q_0.8.1_darwin_amd64.tar.gz"
      sha256 "f09a33d6941682e4108c1849dec3d234fd9e483c9d9c05ba6fde5b1aa5597fd9"

      def install
        bin.install "q"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natesales/q/releases/download/v0.8.1/q_0.8.1_linux_arm64.tar.gz"
      sha256 "b783f6adbb7999d81ea10f3baa488c740c8b887bde390f6c08fcc3647991ea44"

      def install
        bin.install "q"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/natesales/q/releases/download/v0.8.1/q_0.8.1_linux_amd64.tar.gz"
      sha256 "5094ce4cb11ff6df880499f6c1cf12b7a65ff89fbc8839c37aa5fe1f11fa85dd"

      def install
        bin.install "q"
      end
    end
  end
end
