# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Q < Formula
  desc ""
  homepage "https://github.com/natesales/repo"
  version "0.14.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/natesales/q/releases/download/v0.14.0/q_0.14.0_darwin_arm64.tar.gz"
      sha256 "20655cf7204a90fb48dead3223b8fdebead8b5abf52740cbde878c738c777af0"

      def install
        bin.install "q"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/natesales/q/releases/download/v0.14.0/q_0.14.0_darwin_amd64.tar.gz"
      sha256 "80c62b6cd5181f5cdfa2829caa3e0a2c48e6841ace7c47a51b21428320e5db08"

      def install
        bin.install "q"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/natesales/q/releases/download/v0.14.0/q_0.14.0_linux_amd64.tar.gz"
      sha256 "32887c95ff29ef252e70a15145bdfa9a881da4fe815be24e49751ebb9930799b"

      def install
        bin.install "q"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/natesales/q/releases/download/v0.14.0/q_0.14.0_linux_arm64.tar.gz"
      sha256 "4798459e56b8b739835dd3b8bab194e2d045adad96341ccd4dca203aa4ea1b12"

      def install
        bin.install "q"
      end
    end
  end
end
